"""add squads

Revision ID: 5797d0ee5642
Revises: c4981ea3d993
Create Date: 2019-08-03 16:00:45.201472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5797d0ee5642'
down_revision = 'c4981ea3d993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attacking_squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('eventcol_id', sa.Integer(), nullable=True),
    sa.Column('attacking_squad_race', sa.String(length=20), nullable=True),
    sa.Column('attacking_squad_entity_pop', sa.Integer(), nullable=True),
    sa.Column('attacking_squad_number', sa.Integer(), nullable=True),
    sa.Column('attacking_squad_deaths', sa.Integer(), nullable=True),
    sa.Column('attacking_squad_site', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defending_squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('eventcol_id', sa.Integer(), nullable=True),
    sa.Column('defending_squad_race', sa.String(length=20), nullable=True),
    sa.Column('defending_squad_entity_pop', sa.Integer(), nullable=True),
    sa.Column('defending_squad_number', sa.Integer(), nullable=True),
    sa.Column('defending_squad_deaths', sa.Integer(), nullable=True),
    sa.Column('defending_squad_site', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defending_squads')
    op.drop_table('attacking_squads')
    # ### end Alembic commands ###
