"""add worship_id

Revision ID: cc90efededb0
Revises: 14ddba349c06
Create Date: 2019-08-26 21:44:19.850298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc90efededb0'
down_revision = '14ddba349c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('worship_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'worship_id')
    # ### end Alembic commands ###
