"""add pop, fix rep

Revision ID: 4f8be17a3e8a
Revises: dd300bea6d51
Create Date: 2019-06-18 20:52:58.253385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8be17a3e8a'
down_revision = 'dd300bea6d51'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_populations',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=20), nullable=True),
    sa.Column('civ_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.add_column('relationship', sa.Column('rep_buddy', sa.Integer(), nullable=True))
#    op.drop_column('relationship', 'rep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationship', sa.Column('rep', sa.INTEGER(), nullable=True))
    op.drop_column('relationship', 'rep_buddy')
    op.drop_table('entity_populations')
    # ### end Alembic commands ###
