"""historical_eras

Revision ID: 854a2e07f184
Revises: 6ff01e4f57c7
Create Date: 2019-05-20 16:28:54.360110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854a2e07f184'
down_revision = '6ff01e4f57c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_eras',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_eras')
    # ### end Alembic commands ###
