"""rem link_types

Revision ID: a9199e944e16
Revises: c11323d34060
Create Date: 2019-06-06 19:50:00.224318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9199e944e16'
down_revision = 'c11323d34060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hf_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hf_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('df_world_id', sa.INTEGER(), nullable=True),
    sa.Column('hfid1', sa.INTEGER(), nullable=True),
    sa.Column('hfid2', sa.INTEGER(), nullable=True),
    sa.Column('link_strength', sa.INTEGER(), nullable=True),
    sa.Column('link_type', sa.VARCHAR(length=6), nullable=True),
    sa.CheckConstraint("link_type IN ('child', 'spouse')"),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid1'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid2'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
