"""empty message

Revision ID: b8fa8253371c
Revises: f05ae07e9782
Create Date: 2020-10-06 14:39:22.919731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fa8253371c'
down_revision = 'f05ae07e9782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('df_world', sa.Column('height_coords', sa.Integer(), nullable=True))
    op.add_column('df_world', sa.Column('height_pixels', sa.Integer(), nullable=True))
    op.add_column('df_world', sa.Column('width_coords', sa.Integer(), nullable=True))
    op.add_column('df_world', sa.Column('width_pixels', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('df_world', 'width_pixels')
    op.drop_column('df_world', 'width_coords')
    op.drop_column('df_world', 'height_pixels')
    op.drop_column('df_world', 'height_coords')
    # ### end Alembic commands ###
