"""many new models

Revision ID: bbcc6e5896fe
Revises: e1b7a5bf2dff
Create Date: 2019-05-26 00:34:38.301792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcc6e5896fe'
down_revision = 'e1b7a5bf2dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dance_forms',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('entities',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('historical_events',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('musical_forms',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('poetic_forms',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('regions',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('Wetland', 'Grassland', 'Hills', 'Desert', 'Forest', 'Mountains', 'Lake', 'Ocean', 'Tundra', 'Glacier'), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('sites',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('coords', sa.String(length=10), nullable=True),
    sa.Column('rectangle', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Enum('cave', 'fortress', 'dark fortress', 'forest retreat', 'town', 'vault', 'hillocks', 'dark pits', 'hamlet', 'tomb', 'mountain halls', 'camp', 'lair', 'shrine'), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('underground_regions',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('cavern', 'magma', 'underworld'), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('world_constructions',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('coords', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('competitor_hfid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'competitor_hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'event_id'], ['historical_events.df_world_id', 'historical_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_position_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('position_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'entity_id'], ['entities.df_world_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_reputations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('first_ageless_season_count', sa.Integer(), nullable=True),
    sa.Column('first_ageless_year', sa.Integer(), nullable=True),
    sa.Column('unsolved_murders', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'entity_id'], ['entities.df_world_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('hfid', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('create a great work of art', 'immortality', 'master a skill', 'start a family', 'rule the world', 'fall in love', 'see the great natural sites', 'become a legendary warrior', 'bring peace to the world', 'make a great discovery'), nullable=False),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'hfid', 'goal')
    )
    op.create_table('hf_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid1', sa.Integer(), nullable=True),
    sa.Column('hfid2', sa.Integer(), nullable=True),
    sa.Column('link_strength', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.Enum('child', 'spouse'), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid1'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid2'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_knowledges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid', sa.Integer(), nullable=True),
    sa.Column('interaction_knowledge', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid', sa.Integer(), nullable=True),
    sa.Column('journey_pet', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid1', sa.Integer(), nullable=True),
    sa.Column('hfid2', sa.Integer(), nullable=True),
    sa.Column('known_identity_id', sa.Integer(), nullable=True),
    sa.Column('last_meet_seconds72', sa.Integer(), nullable=True),
    sa.Column('last_meet_year', sa.Integer(), nullable=True),
    sa.Column('meet_count', sa.Integer(), nullable=True),
    sa.Column('rep', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid1'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid2'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.Enum('lair', 'home structure', 'seat of power', 'occupation'), nullable=True),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'entity_id'], ['entities.df_world_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'site_id'], ['sites.df_world_id', 'sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid', sa.Integer(), nullable=True),
    sa.Column('total_ip', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spheres',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('hfid', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.Enum('fire', 'wealth', 'caverns', 'misery', 'water', 'deformity', 'depravity', 'death', 'thralldom', 'chaos', 'blight', 'disease', 'treachery', 'suicide', 'nightmares', 'torture', 'animals', 'nature', 'plants', 'rivers', 'jewels', 'minerals', 'metals', 'mountains', 'fortresses', 'war', 'wisdom', 'scholarship', 'writing', 'victory', 'volcanos', 'night', 'trickery', 'lies', 'oceans', 'speech', 'theft', 'forgiveness', 'mercy', 'creation', 'birth', 'youth', 'longevity', 'song', 'truth', 'crafts', 'family', 'children', 'murder', 'healing', 'lightning', 'dreams', 'rumors', 'fish', 'fishing', 'hunting', 'strength', 'light', 'thunder', 'food'), nullable=False),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'hfid', 'sphere')
    )
    op.create_table('structures',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('underworld spire', 'inn tavern', 'market', 'temple', 'dungeon', 'keep', 'tomb', 'mead hall', 'library'), nullable=True),
    sa.Column('subtype', sa.Enum('catacombs', 'standard'), nullable=True),
    sa.Column('worship_hfid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'entity_id'], ['entities.df_world_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'site_id'], ['sites.df_world_id', 'sites.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'worship_hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'site_id', 'entity_id', 'local_id')
    )
    op.create_table('written_contents',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('form', sa.Enum('musical composition', 'choreography', 'pom', 'guide', 'essay', 'manual', 'cultural history', 'star chart', 'letter', 'short story', 'cultural composition', 'novel', 'autobiography', 'comparative biography', 'biography'), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('author_hfid', sa.Integer(), nullable=True),
    sa.Column('author_roll', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'author_hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'id')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(length=10), nullable=True),
    sa.Column('magnitude', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'content_id'], ['written_contents.df_world_id', 'written_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artifacts', sa.Column('name_string', sa.String(length=50), nullable=True))
    op.add_column('artifacts', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('artifacts', sa.Column('written_content_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'written_content_id')
    op.drop_column('artifacts', 'page_number')
    op.drop_column('artifacts', 'name_string')
    op.drop_table('styles')
    op.drop_table('written_contents')
    op.drop_table('structures')
    op.drop_table('spheres')
    op.drop_table('skills')
    op.drop_table('site_links')
    op.drop_table('relationship')
    op.drop_table('journey_pets')
    op.drop_table('interaction_knowledges')
    op.drop_table('hf_links')
    op.drop_table('goals')
    op.drop_table('entity_reputations')
    op.drop_table('entity_position_links')
    op.drop_table('competitors')
    op.drop_table('world_constructions')
    op.drop_table('underground_regions')
    op.drop_table('sites')
    op.drop_table('regions')
    op.drop_table('poetic_forms')
    op.drop_table('musical_forms')
    op.drop_table('historical_events')
    op.drop_table('entities')
    op.drop_table('dance_forms')
    # ### end Alembic commands ###
