"""add fixed goals

Revision ID: c11323d34060
Revises: 2b951a799790
Create Date: 2019-06-06 18:46:37.932185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11323d34060'
down_revision = '2b951a799790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('df_world_id', sa.Integer(), nullable=False),
    sa.Column('hfid', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('create a great work of art', 'immortality', 'master a skill', 'start a family', 'rule the world', 'fall in love', 'see the great natural sites', 'become a legendary warrior', 'bring peace to the world', 'make a great discovery', 'craft a masterwork'), nullable=False),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id'], ['df_world.id'], ),
    sa.PrimaryKeyConstraint('df_world_id', 'hfid', 'goal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    # ### end Alembic commands ###
