"""readd link_types

Revision ID: dd300bea6d51
Revises: a9199e944e16
Create Date: 2019-06-06 19:50:39.291237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd300bea6d51'
down_revision = 'a9199e944e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hf_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid1', sa.Integer(), nullable=True),
    sa.Column('hfid2', sa.Integer(), nullable=True),
    sa.Column('link_strength', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.Enum('child', 'spouse', 'deity', 'apprentice', 'mother', 'father', 'former apprentice', 'master', 'former master'), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid1'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid2'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hf_links')
    # ### end Alembic commands ###
