"""add entity_link

Revision ID: e4830a382cf3
Revises: b6fbf6b90ab2
Create Date: 2019-06-05 17:59:12.432010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4830a382cf3'
down_revision = 'b6fbf6b90ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('df_world_id', sa.Integer(), nullable=True),
    sa.Column('hfid', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['df_world_id', 'entity_id'], ['entities.df_world_id', 'entities.id'], ),
    sa.ForeignKeyConstraint(['df_world_id', 'hfid'], ['historical_figures.df_world_id', 'historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_links')
    # ### end Alembic commands ###
