"""empty message

Revision ID: f975ff3c2290
Revises: b184f98a1526
Create Date: 2019-06-23 18:32:11.687095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f975ff3c2290'
down_revision = 'b184f98a1526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_column('historical_events', 'site_id_2')
#    op.drop_column('historical_events', 'building_id')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_events', sa.Column('building_id', sa.INTEGER(), nullable=True))
    op.add_column('historical_events', sa.Column('site_id_2', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
