"""add skill to skill

Revision ID: b282e6c7beb2
Revises: e4830a382cf3
Create Date: 2019-06-05 18:36:14.901404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b282e6c7beb2'
down_revision = 'e4830a382cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skill', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'skill')
    # ### end Alembic commands ###
