import React from 'react';
import { BrowserRouter as Route, Link } from 'react-router-dom';

function Index() {
	return (
		<span>
		<h1> Welcome to Legendshub </h1>

		<p>
			Legendshub is a web-based legends browser for the game <a href="http://www.bay12games.com/dwarves/">Dwarf Fortress</a>.
			If you're not familliar with the game or with legends mode in 
			particular, you can find a good initial explanation on the <a href="https://dwarffortresswiki.org/index.php/DF2014:Legends#Legends_Utilities">wiki</a>.
		</p>
		<p>
			It's built upon a custom-built XML stream parser, which saves all
			of your legends data generated by the game to a database for easy
			querying. Because Legendshub is based on the web, it's easy to share
			your favorite discoveries with others around the world.
		</p>
		<p>
			As you can see, Legendshub is still very much under construction.
			The parser and the underlying data strctures are up an running, 
			but we're still working through writing all of the copy, and
			creating some of the visualization tools to display it to readers.
			We'll have to get some styling up and running as well. 
			One day, anybody will be able to upload their files to share. 
			For now, you can start exploring one of the worlds we've created
			by clicking <Link to={`/1`}>here</Link>.
		</p>
		<p>
			You can follow our progress on <a href="https://github.com/imcgeoch/flask_legends">Github</a>!
			If you have any questions or would like to help out, drop us a line
			on Github. Happy exploring!
		</p>
		<p>
			(c) 2020 Ian McGeoch
		</p>
	</span>

	)
}

export default Index;
